export const HOST_BALANCER_STRATEGIES = {
    LEAST_ASSIGNED: 'LEAST_ASSIGNED',
    WEIGHTED: 'WEIGHTED',
    RANDOM: 'RANDOM',
    PRIORITY_FAILOVER: 'PRIORITY_FAILOVER',
    LEAST_TRAFFIC: 'LEAST_TRAFFIC',
    WEIGHTED_LEAST_TRAFFIC: 'WEIGHTED_LEAST_TRAFFIC',
} as const;

export const HOST_BALANCER_UNAVAILABLE_POLICIES = {
    HIDE_HOST: 'HIDE_HOST',
    ORIGINAL_HOST: 'ORIGINAL_HOST',
    KEEP_LAST_IF_POSSIBLE: 'KEEP_LAST_IF_POSSIBLE',
} as const;

export const HOST_BALANCER_TRAFFIC_METRICS = {
    CURRENT_PERIOD: 'CURRENT_PERIOD',
    LAST_24H: 'LAST_24H',
    LAST_6H: 'LAST_6H',
    LAST_1H: 'LAST_1H',
} as const;

export const HOST_BALANCER_TARGET_STATUSES = {
    ACTIVE: 'ACTIVE',
    DRAINING: 'DRAINING',
    DISABLED: 'DISABLED',
    DEAD: 'DEAD',
} as const;
